source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'
use_frameworks!

# Add Application pods here
pod 'Swiftz'
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :tag => 'null-string-beta-2'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :tag => 'null-string-beta-2'
pod 'Alamofire'
pod 'Argo'
pod 'RxSwift'
pod 'RxCocoa'

target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'
  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :tag => 'null-string-beta-2'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :tag => 'null-string-beta-2'
  pod 'Alamofire'
  pod 'OHHTTPStubs'
  pod 'RxSwift'
  pod 'RxCocoa'
end

<% if enable_settings && use_cocoapods %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>
